import { MaskConfig, MaskPreset } from '../types/mask';

export const MASK_PRESETS: MaskPreset[] = [
  {
    id: 'catwoman_petite',
    name: 'Gatúbela Petite Látex',
    category: 'Felino y Sensual',
    subtitle: 'Antifaz pequeño y ceñido en látex brillante con orejas felinas, mirada rasgada y costuras.',
    defaultPrimaryColor: '#090A0F',
    defaultSecondaryColor: '#E11D48',
    defaultCoverEyes: false,
    defaultScaleWidth: 0.9,
    defaultScaleHeight: 0.84,
  },
  {
    id: 'catwoman_lace',
    name: 'Gatúbela Encaje Boudoir',
    category: 'Felino y Sensual',
    subtitle: 'Micro-antifaz sensual en tul y encaje negro semitransparente con silueta felina.',
    defaultPrimaryColor: '#111118',
    defaultSecondaryColor: '#F43F5E',
    defaultCoverEyes: false,
    defaultScaleWidth: 0.92,
    defaultScaleHeight: 0.86,
  },
  {
    id: 'feline_noir',
    name: 'Sirena Cat-Eye Charol',
    category: 'Felino y Sensual',
    subtitle: 'Silueta cat-eye ultra estrecha y elevada con acabado charol y destellos en las sienes.',
    defaultPrimaryColor: '#0A0D14',
    defaultSecondaryColor: '#FB7185',
    defaultCoverEyes: false,
    defaultScaleWidth: 0.94,
    defaultScaleHeight: 0.82,
  },
  {
    id: 'domino_classic',
    name: 'Clásico Antifaz Domino',
    category: 'Héroe y Sigilo',
    subtitle: 'Curvatura clásica de antifaz en cuero satinado con contorno anatómico.',
    defaultPrimaryColor: '#11131A',
    defaultSecondaryColor: '#E11D48',
    defaultCoverEyes: false,
    defaultScaleWidth: 0.96,
    defaultScaleHeight: 0.9,
  },
  {
    id: 'venetian_gold',
    name: 'Gala Veneciana Imperial',
    category: 'Gala y Antifaz',
    subtitle: 'Antifaz de etiqueta con filigrana dorada, arabescos y puntas aladas.',
    defaultPrimaryColor: '#7F1D1D',
    defaultSecondaryColor: '#F59E0B',
    defaultCoverEyes: false,
    defaultScaleWidth: 1.04,
    defaultScaleHeight: 1.0,
  },
  {
    id: 'stealth_angular',
    name: 'Sigilo Táctico Facetado',
    category: 'Héroe y Sigilo',
    subtitle: 'Geometría poligonal en fibra mate con aristas sobre el arco superciliar.',
    defaultPrimaryColor: '#1E293B',
    defaultSecondaryColor: '#38BDF8',
    defaultCoverEyes: true,
    defaultScaleWidth: 1.0,
    defaultScaleHeight: 0.95,
  },
  {
    id: 'harlequin_royal',
    name: 'Arlequín Bicolor Real',
    category: 'Gala y Antifaz',
    subtitle: 'Diseño simétrico partido en dos tonos con coronación central en rombo.',
    defaultPrimaryColor: '#1E1B4B',
    defaultSecondaryColor: '#EAB308',
    defaultCoverEyes: false,
    defaultScaleWidth: 1.02,
    defaultScaleHeight: 0.98,
  },
  {
    id: 'cyber_visor',
    name: 'Visor Óptico Luminiscente',
    category: 'Héroe y Sigilo',
    subtitle: 'Lente envolvente continua con líneas de escaneo óptico sobre la mirada.',
    defaultPrimaryColor: '#090D16',
    defaultSecondaryColor: '#06B6D4',
    defaultCoverEyes: true,
    defaultScaleWidth: 1.02,
    defaultScaleHeight: 0.88,
  },
  {
    id: 'editorial_censor',
    name: 'Censura Editorial Directa',
    category: 'Privacidad y Censura',
    subtitle: 'Franja de anonimización documental con sello tipográfico opcional.',
    defaultPrimaryColor: '#050505',
    defaultSecondaryColor: '#E11D48',
    defaultCoverEyes: true,
    defaultScaleWidth: 1.0,
    defaultScaleHeight: 0.8,
  },
  {
    id: 'pixel_mosaic',
    name: 'Antifaz Pixelado Dinámico',
    category: 'Privacidad y Censura',
    subtitle: 'Mosaico en tiempo real recortado con forma de antifaz sobre los ojos.',
    defaultPrimaryColor: '#18181B',
    defaultSecondaryColor: '#A1A1AA',
    defaultCoverEyes: true,
    defaultScaleWidth: 1.0,
    defaultScaleHeight: 0.92,
  },
  {
    id: 'frosted_glass',
    name: 'Cristal Esmerilado Privado',
    category: 'Privacidad y Censura',
    subtitle: 'Lente translúcida difuminada con bisel especular para ocultar la identidad.',
    defaultPrimaryColor: '#334155',
    defaultSecondaryColor: '#E2E8F0',
    defaultCoverEyes: true,
    defaultScaleWidth: 1.0,
    defaultScaleHeight: 0.9,
  },
  {
    id: 'custom_image',
    name: 'Antifaz PNG / SVG Propio',
    category: 'Gala y Antifaz',
    subtitle: 'Sube cualquier imagen con fondo transparente para anclarla al rostro.',
    defaultPrimaryColor: '#E11D48',
    defaultSecondaryColor: '#F59E0B',
    defaultCoverEyes: false,
    defaultScaleWidth: 1.0,
    defaultScaleHeight: 1.0,
  },
];

export const DEFAULT_MASK_CONFIG: MaskConfig = {
  styleId: 'catwoman_petite',
  primaryColor: '#090A0F',
  secondaryColor: '#E11D48',
  scaleWidth: 0.9,
  scaleHeight: 0.84,
  offsetY: -0.01,
  opacity: 0.97,
  shadowIntensity: 0.72,
  coverEyes: false,
  eyeTintOpacity: 0.82,
  smoothing: 0.55,
  censorText: 'CONFIDENCIAL',
  pixelBlockSize: 12,
  showTrackingGuides: false,
  customImageUrl: null,
  earHeight: 1.05,
  eyeSlant: 0.24,
  glossIntensity: 0.88,
  showStitches: true,
};

export const COLOR_SWATCHES = [
  { name: 'Látex Noir Carmesí', primary: '#090A0F', secondary: '#E11D48' },
  { name: 'Gatúbela Costura Blanca', primary: '#090A0F', secondary: '#F8FAFC' },
  { name: 'Terciopelo Burdeos', primary: '#4C0519', secondary: '#FB7185' },
  { name: 'Charol Violeta Noir', primary: '#1E1B4B', secondary: '#C084FC' },
  { name: 'Oro Veneciano', primary: '#78350F', secondary: '#FDE047' },
  { name: 'Esmeralda Sirena', primary: '#022C22', secondary: '#34D399' },
  { name: 'Titanio Plateado', primary: '#18181B', secondary: '#94A3B8' },
  { name: 'Encaje Marfil', primary: '#F8FAFC', secondary: '#E11D48' },
];
